baseUrl=https://parabank.parasoft.com/parabank/index.htm
firstName=Sid
lastName=Upadhyay
address=123 Test Street
city=Hyderabad
state=Telangana
zip=500001
phone=9999999999
userName=siduser
password=Test@12345
